stages:
  - check

variables:
  R_LIBS_USER: "$CI_PROJECT_DIR/ci/lib"

default:
  tags: [docker]

cache:
  key: "airGRdatassim-${R_VERSION}"
  paths:
    - $R_LIBS_USER

before_script:
  - mkdir -p $R_LIBS_USER
  - echo "R_LIBS='$R_LIBS_USER'" > .Renviron
  - R -e 'remotes::install_deps(dependencies = TRUE)'
  - R -e 'remotes::install_gitlab("HYCAR-Hydro/airgr@dev", host = "gitlab.irstea.fr")'

.R-devel:
  image: rocker/verse:devel
  variables:
    R_VERSION: devel

.R-patched:
  only:
    refs:
      - tags
      - schedules
  image: rocker/verse:latest
  variables:
    R_VERSION: patched

.check:
  stage: check
  script:
    - tlmgr install ec && tlmgr install cm-super
    - R -e 'remotes::update_packages("rcmdcheck")'
    - R -e 'rcmdcheck::rcmdcheck(args = "--as-cran", error_on = "warning")'

check_patched:
  extends:
    - .check
    - .R-patched

check_devel:
  extends:
    - .check
    - .R-devel
