stages:
  - update_packages
  - build
  - tests

default:
  before_script:
    - echo "setwd(\"$(pwd)\")" > .Rprofile
    - PATH=~/R/sources/R-${R_VERSION}/bin:$PATH
    - rename "s/${R_VERSION}.airGRdatassim/airGRdatassim/" *.tar.gz

.update_packages:
  stage: update_packages
  only:
    refs:
      - tags
      - schedules
  script:
    - Rscript -e "update.packages(ask=FALSE, repos=\"http://cran.r-project.org\")"

.build:
  stage: build
  script:
    - cd ..
    - echo "setwd(\"$(pwd)\")" > .Rprofile
    - R CMD build airgrdatassim
    - rename "s/airGRdatassim/${R_VERSION}.airGRdatassim/" airGRdatassim_*.tar.gz
    - mv *.tar.gz airgrdatassim/
  artifacts:
    untracked: true
    expire_in: 1 week

.check_as_cran:
  stage: tests
  script:
    - R CMD check --as-cran airGR_*.tar.gz

build_patched:
  variables:
    R_VERSION: "patched"
  extends: .build

build_devel:
  only:
    refs:
      - tags
      - schedules
  variables:
    R_VERSION: "devel"
  extends: .build

build_oldrel:
  only:
    refs:
      - tags
      - schedules
  variables:
    R_VERSION: "oldrel"
  extends: .build

check_as_cran_patched:
  variables:
    R_VERSION: "patched"
  extends: .check_as_cran

check_as_cran_devel:
  only:
    refs:
      - tags
      - schedules
  variables:
    R_VERSION: "devel"
  extends: .check_as_cran

check_as_cran_oldrel:
  only:
    refs:
      - tags
      - schedules
  variables:
    R_VERSION: "oldrel"
  extends: .check_as_cran

